#!/usr/bin/perl -w
undef $/;
use constant CATLO=>0x130;
use constant CATHI=>0x198;
use constant DATASTART=>0xa00;
my @files=qw[
    intro.exo
    intro
    code.exo
    tiles.exo
    title.exo
    level01 level02 level03 level04 level05
    level06 level07 level08 level09 level10
    level11 level12 level13 level14 level15
    level16 level17 level18 level19 level20
    level21 level22 level23 level24 level25

    ];
#electron.exo
#    game_beeb.exo
#    game_b+.exo
    #title
    #game_beeb
    #game_master
    # save1 save2 save3 save4

my $nfiles=scalar @files;

if (@ARGV && shift=~/^-f/) {
    print "; autogenerated by makedisc.pl\n";
    for my $i (0..$nfiles-1) {
	printf "FILE_%s = %d\n", ($files[$i]=~s/\./_/rg), $i;
    }
    exit;
}

my @lengths = map { (stat($_))[7] or die $_} @files;

my $cat = pack"v*",@lengths;

use List::MoreUtils qw(part);
{my $i=0;$cat=join"",map {@$_} part {$i++%2} split//,$cat;}

my $disc=<>;

substr($disc,CATLO,$nfiles,substr($cat,0,$nfiles));
substr($disc,CATHI,$nfiles,substr($cat,$nfiles));
my $off=0xa00;
print STDERR "Index\tOffset\tLength\tName\n";
for my $i (0..$nfiles-1) {
    printf STDERR "%d\t%x\t%x\t%s\n", $i, $off, $lengths[$i], $files[$i];
    $off+=$lengths[$i];
}

my @data = map { open my $f,"<",$_ or die;<$f> } @files;
my $data = join"",@data;

$disc=$disc.("\0"x (0xa00-length($disc))) if length$disc<0xa00;
die length($disc) if length($disc) !=0xa00;
$disc.=$data;



print $disc;
exit;
__END__
my @data = map { open my $f,"<",$_ or die;<$f> } @files;
my $data = join"",@data;

substr($disc,

# sub pack_fn {
#     my $fn=shift;
#     my $dir=shift || '$';
#     pack"A7C",$fn,$dir;
# }

# my $title="DROD";
    
# my $datafile="data";
# my $bootcode="boot";
# my $bootload=0xff1900;
# my $bootexec=0xff1900;
#my $sec0 = pack"A8", substr($title,0,8), '!BOOT  $', $datafile;
#my $sec1 = pack"A4CCCC", substr($title,8,4), 0, 
#$sec0.="\x00"x(256-length($sec0));
#$sec1.="\x00"x(256-length($sec0));
